name: test

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install blosc (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pip install blosc --no-input --target src/test/resources
          mv src/test/resources/bin/* src/test/resources
      - name: Install blosc (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install blosc --no-input --target src/test/resources
          mv src/test/resources/lib64/* src/test/resources
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn -B clean test --file pom.xml
